name: on pull-request jobs

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci app
  check-database-types:
    runs-on: ubuntu-latest
    env:
      OAUTH_GOOGLE_SECRET: ${{ secrets.OAUTH_GOOGLE_SECRET }}
      OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_SECRET }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.167.4
      - name: link supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - name: verify migrations are healthy
        run: supabase db push --dry-run
      - name: start supabase
        run: supabase db start
      - name: verify generates types are up to date
        run: |
          supabase gen types typescript --local > supabase/functions/database.types.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet supabase/functions/database.types.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Enforce client passes typechecker
        run: pnpm run typecheck
  build-serverless-functions:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: DUMMY_KEY
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.0
      - name: Enforce edge function passes typechecker
        run: deno check supabase/functions/**/*.ts --import-map=supabase/functions/import_map.json
      - name: Run Deno tests
        run: deno test --import-map=supabase/functions/import_map.json --allow-env --allow-net --allow-read supabase/functions/tests
